/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifdef OB_OBJ_PRIV_TYPE_DEF
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_NONE, "")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_ALTER, "ALTER")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_AUDIT, "AUDIT")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_COMMENT, "COMMENT")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_DELETE, "DELETE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_GRANT, "GRANT")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_INDEX, "INDEX")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_INSERT, "INSERT")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_LOCK, "LOCK")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_RENAME, "RENAME")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_SELECT, "SELECT")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_UPDATE, "UPDATE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_REFERENCES, "REFERENCES")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_EXECUTE, "EXECUTE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_CREATE, "CREATE")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_FLASHBACK, "FLASHBACK")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_READ, "READ")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_WRITE, "WRITE")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_DEBUG, "DEBUG")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_USE_CATALOG, "USE CATALOG")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_MAX, "")
#endif

/* to do, No! May be no do forever. */
#ifdef asfasgasgfa 

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_ENQUEUE, "ENQUEUE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_DEQUEUE, "DEQUEUE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_UNDER, "UNDER")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_ON_COMMIT_REFRESH, "ON COMMIT REFRESH")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_QUERY_REWRITE, "QUERY REWRITE")
/* index */
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_MERGE_VIEW, "MERGE VIEW")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_USE, "USE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_FLASHBACK_ARCHIVE, "FLASHBACK ARCHIVE")

#endif

#ifndef OCEANBASE_SHARE_SCHEMA_OB_OBJ_PRIV_TYPE_
#define OCEANBASE_SHARE_SCHEMA_OB_OBJ_PRIV_TYPE_

enum OB_RAW_OBJ_PRIV_ID 
{
#define OB_OBJ_PRIV_TYPE_DEF(priv_id, priv_name) priv_id,
#include "share/schema/ob_obj_priv_type.h"
#undef OB_OBJ_PRIV_TYPE_DEF

};

#endif /* OB_OBJ_PRIV_TYPE_ */
