/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_SJIS_JAPANESE_CI, 42);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_SJIS_BIN, 43);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_BIG5_CHINESE_CI, 44);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_BIG5_BIN, 45);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_HKSCS_BIN, 46);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_HKSCS31_BIN, 47);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ICELANDIC_UCA_CI, 48);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LATVIAN_UCA_CI, 49);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ROMANIAN_UCA_CI, 50);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SLOVENIAN_UCA_CI, 51);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_POLISH_UCA_CI, 52);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ESTONIAN_UCA_CI, 53);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SPANISH_UCA_CI, 54);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SWEDISH_UCA_CI, 55);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_TURKISH_UCA_CI, 56);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CZECH_UCA_CI, 57);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DANISH_UCA_CI, 58);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LITHUANIAN_UCA_CI, 59);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SLOVAK_UCA_CI, 60);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SPANISH2_UCA_CI, 61);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ROMAN_UCA_CI, 62);

} // end sql
} // end oceanbase
