/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_DANISH_CI, 21);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_GERMAN2_CI, 22);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_BIN, 23);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_GENERAL_CI, 24);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_GENERAL_CS, 25);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_SPANISH_CI, 26);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB2312_CHINESE_CI, 27);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB2312_BIN, 28);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_BIN, 29);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CI, 30);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CS, 31);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CI, 32);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CS, 33);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CI, 34);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CS, 35);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_ASCII_GENERAL_CI, 36);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_ASCII_BIN, 37);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_TIS620_THAI_CI, 38);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_TIS620_BIN, 39);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16LE_GENERAL_CI, 40);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16LE_BIN, 41);

} // end sql
} // end oceanbase
