/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SR_LATN_0900_AI_CI, 147);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SR_LATN_0900_AS_CS, 148);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BS_0900_AI_CI, 149);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BS_0900_AS_CS, 150);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BG_0900_AI_CI, 151);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BG_0900_AS_CS, 152);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GL_0900_AI_CI, 153);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GL_0900_AS_CS, 154);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_MN_CYRL_0900_AI_CI, 155);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_MN_CYRL_0900_AS_CS, 156);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_DEC8_SWEDISH_CI, 157);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_DEC8_BIN, 158);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_CP850_GENERAL_CI, 159);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_CP850_BIN, 160);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_HP8_ENGLISH_CI, 161);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_HP8_BIN, 162);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_MACROMAN_GENERAL_CI, 163);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_MACROMAN_BIN, 164);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_SWE7_SWEDISH_CI, 165);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_SWE7_BIN, 166);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_MAX, 167);

} // end sql
} // end oceanbase
